version: '3.3'
services:
  whoami:
    image: emilevauge/whoami
    hostname: 'whoami-{{.Task.Slot}}'
    environment:
      SLOT: '{{.Task.Slot}}'
      SERVICE: '{{.Service.Name}}'
      STACK: '{{index .Service.Labels "com.docker.stack.namespace"}}'
    networks:
      traefik:
    deploy:
      replicas: 3
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.backend=whoami
        - traefik.frontend.rule=Host:whoami.server.test
        - traefik.docker.network=traefik_traefik

networks:
  traefik:
    external:
       name: traefik_traefik
